version: '3'

services:
  jitsi-keycloak:
    build:
      context: .
    container_name: jitsi-keycloak
    restart: unless-stopped
    environment:
      JITSI_SECRET: 123456789
      DEFAULT_ROOM: meeting
      JITSI_URL: https://suncat.io
    volumes:
      - ./config:/config
    ports:
      - 3000:3000

    networks:
      - local

networks:
  local:
    name: local
    driver: bridge
